/** A universe-lore entry as generated by the model, before it becomes a WI entry. */
export interface GeneratedEntry {
  title: string;
  keys: string[];
  content: string;
}

/** Validate/normalize one candidate entry; returns null if it isn't usable. */
function coerceEntry(x: unknown): GeneratedEntry | null {
  if (!x || typeof x !== 'object') return null;
  const o = x as Record<string, unknown>;

  const title =
    typeof o.title === 'string' ? o.title.trim() : typeof o.comment === 'string' ? o.comment.trim() : '';
  const content = typeof o.content === 'string' ? o.content.trim() : '';
  const rawKeys = Array.isArray(o.keys) ? o.keys : Array.isArray(o.key) ? o.key : [];
  const keys = [
    ...new Set(
      rawKeys.filter((k): k is string => typeof k === 'string').map((k) => k.trim()).filter(Boolean),
    ),
  ];

  if (!title || !content || keys.length === 0) return null;
  return { title, keys, content };
}

/** Extract the entries array from a model response, tolerating fences/prose/object-wrapping. */
function extractEntriesArray(raw: string): unknown[] {
  const stripped = raw.replace(/```(?:json)?/gi, '').trim();
  const lb = stripped.indexOf('[');
  const rb = stripped.lastIndexOf(']');
  const lc = stripped.indexOf('{');
  const rc = stripped.lastIndexOf('}');

  let jsonText: string;
  if (lb !== -1 && rb > lb) jsonText = stripped.slice(lb, rb + 1);
  else if (lc !== -1 && rc > lc) jsonText = stripped.slice(lc, rc + 1);
  else throw new Error('parseGenerationResponse: no JSON array or object found');

  const parsed = JSON.parse(jsonText);
  if (Array.isArray(parsed)) return parsed;
  if (parsed && typeof parsed === 'object' && Array.isArray((parsed as { entries?: unknown }).entries)) {
    return (parsed as { entries: unknown[] }).entries;
  }
  throw new Error('parseGenerationResponse: expected an array of entries');
}

/**
 * Parse a generation response into validated {@link GeneratedEntry} objects.
 * Malformed entries are dropped; throws only if no array/object can be found at all.
 */
export function parseGenerationResponse(raw: string): GeneratedEntry[] {
  return extractEntriesArray(raw)
    .map(coerceEntry)
    .filter((e): e is GeneratedEntry => e !== null);
}

/** Build the focused-core generation prompt (ADR-0005). Pure — unit-testable. */
export function buildGenerationPrompt(franchiseDisplay: string, targetCount: number): string {
  return [
    `You are writing a shared WORLD-LORE reference for the "${franchiseDisplay}" universe,`,
    'to be used as SillyTavern World Info shared across characters from that setting.',
    '',
    'Produce concise, factual, WORLD-level lore only — factions, locations, technology, history,',
    'core rules, and major recurring characters of the setting. Do NOT write about any single',
    'roleplay character, and do NOT invent deep-cut "canon": stick to well-established facts you',
    'are confident about. Prefer fewer accurate entries over many shaky ones.',
    '',
    `Write about ${targetCount} entries (a focused core, not an exhaustive wiki).`,
    'For each entry:',
    '- "title": a short human label (not shown to the AI).',
    '- "keys": trigger keywords — proper nouns, common synonyms, and plurals people would actually',
    '  type. Avoid generic words. These decide when the entry is injected.',
    '- "content": 1–4 concise sentences of prose. No bracket/attribute-list formatting.',
    '',
    'Respond with ONLY a JSON array — no prose, no code fence — of objects:',
    '[{"title": "...", "keys": ["...", "..."], "content": "..."}]',
  ].join('\n');
}

/**
 * Generate focused-core universe entries via the user's LLM connection.
 * Glue: exercises the host `generateQuietPrompt`. Retries once, requires a non-empty result.
 */
export async function generateUniverseEntries(
  ctx: SillyTavernContext,
  franchiseDisplay: string,
  targetCount: number,
): Promise<GeneratedEntry[]> {
  const prompt = buildGenerationPrompt(franchiseDisplay, targetCount);
  const maxAttempts = 2;
  let lastError: unknown;
  for (let attempt = 0; attempt < maxAttempts; attempt++) {
    const raw = await ctx.generateQuietPrompt(prompt, false, true, undefined, undefined, 2048);
    try {
      const entries = parseGenerationResponse(raw);
      if (entries.length > 0) return entries;
      lastError = new Error('generation returned an empty entry list');
    } catch (error) {
      lastError = error;
    }
  }
  throw new Error(
    `generateUniverseEntries: no usable entries after ${maxAttempts} attempts (${String(lastError)})`,
  );
}
