/** A universe-lore entry as generated by the model, before it becomes a WI entry. */
export interface GeneratedEntry {
  title: string;
  keys: string[];
  content: string;
}

/** Validate/normalize one candidate entry; returns null if it isn't usable. */
function coerceEntry(x: unknown): GeneratedEntry | null {
  if (!x || typeof x !== 'object') return null;
  const o = x as Record<string, unknown>;

  const title =
    typeof o.title === 'string' ? o.title.trim() : typeof o.comment === 'string' ? o.comment.trim() : '';
  const content = typeof o.content === 'string' ? o.content.trim() : '';
  const rawKeys = Array.isArray(o.keys) ? o.keys : Array.isArray(o.key) ? o.key : [];
  const keys = [
    ...new Set(
      rawKeys.filter((k): k is string => typeof k === 'string').map((k) => k.trim()).filter(Boolean),
    ),
  ];

  if (!title || !content || keys.length === 0) return null;
  return { title, keys, content };
}

/** Extract the entries array from a model response, tolerating fences/prose/object-wrapping. */
function extractEntriesArray(raw: string): unknown[] {
  const stripped = raw.replace(/```(?:json)?/gi, '').trim();
  const lb = stripped.indexOf('[');
  const rb = stripped.lastIndexOf(']');
  const lc = stripped.indexOf('{');
  const rc = stripped.lastIndexOf('}');

  let jsonText: string;
  if (lb !== -1 && rb > lb) jsonText = stripped.slice(lb, rb + 1);
  else if (lc !== -1 && rc > lc) jsonText = stripped.slice(lc, rc + 1);
  else throw new Error('parseGenerationResponse: no JSON array or object found');

  const parsed = JSON.parse(jsonText);
  if (Array.isArray(parsed)) return parsed;
  if (parsed && typeof parsed === 'object' && Array.isArray((parsed as { entries?: unknown }).entries)) {
    return (parsed as { entries: unknown[] }).entries;
  }
  throw new Error('parseGenerationResponse: expected an array of entries');
}

/**
 * Parse a generation response into validated {@link GeneratedEntry} objects.
 * Malformed entries are dropped; throws only if no array/object can be found at all.
 */
export function parseGenerationResponse(raw: string): GeneratedEntry[] {
  return extractEntriesArray(raw)
    .map(coerceEntry)
    .filter((e): e is GeneratedEntry => e !== null);
}

/** Build the focused-core generation prompt (ADR-0005). Pure — unit-testable. */
export function buildGenerationPrompt(franchiseDisplay: string, targetCount: number): string {
  return [
    `You are writing a shared WORLD-LORE reference for the "${franchiseDisplay}" universe,`,
    'to be used as SillyTavern World Info shared across characters from that setting.',
    '',
    'Produce concise, factual, WORLD-level lore only — factions, locations, technology, history,',
    'core rules, and major recurring characters of the setting. Do NOT write about any single',
    'roleplay character, and do NOT invent deep-cut "canon": stick to well-established facts you',
    'are confident about. Prefer fewer accurate entries over many shaky ones.',
    '',
    `Write about ${targetCount} entries (a focused core, not an exhaustive wiki).`,
    'For each entry:',
    '- "title": a short human label (not shown to the AI).',
    '- "keys": trigger keywords — proper nouns, common synonyms, and plurals people would actually',
    '  type. Avoid generic words. These decide when the entry is injected.',
    '- "content": 1–4 concise sentences of prose. No bracket/attribute-list formatting.',
    '',
    'Respond with ONLY a JSON array — no prose, no code fence — of objects:',
    '[{"title": "...", "keys": ["...", "..."], "content": "..."}]',
  ].join('\n');
}

/**
 * Build the story-aware prompt for the per-chat book (ADR-0008). Pure — unit-testable.
 * Relies on the ongoing chat being in the model's context (via generateQuietPrompt), so it
 * instructs the model to read the story rather than restating franchise canon.
 */
export function buildStoryPrompt(franchiseDisplay: string, softCap: number): string {
  return [
    `Based on the ROLEPLAY CONVERSATION SO FAR (which you can see above), capture how this`,
    `playthrough of the "${franchiseDisplay}" universe has diverged from its canon.`,
    '',
    'Record two kinds of things:',
    '- World-state changes & events: durable things that happened — places/factions/people whose',
    '  status shifted, things destroyed or created, alliances or conflicts the player caused.',
    '- The player character\'s standing: how NPCs, factions, and the world now regard them —',
    '  reputation, bonds, and grudges earned in play.',
    '',
    'Rules:',
    '- Only durable developments, not passing scene detail or dialogue.',
    '- Do NOT restate established franchise canon — only what THIS story changed or established.',
    "- If nothing notable has happened yet, return an empty array [].",
    `- Keep it focused: up to about ${softCap} entries.`,
    '',
    'For each entry:',
    '- "title": a short human label.',
    '- "keys": trigger keywords (proper nouns, synonyms, plurals) people would actually type.',
    '- "content": 1–3 concise sentences of prose.',
    '',
    'Respond with ONLY a JSON array — no prose, no code fence:',
    '[{"title": "...", "keys": ["...", "..."], "content": "..."}]',
  ].join('\n');
}

/**
 * Generate focused-core FRANCHISE-CANON entries. Glue: uses chat-blind `generateRaw` so the
 * canon book is never influenced by the ongoing roleplay. Retries once; requires a non-empty result.
 */
export async function generateUniverseEntries(
  ctx: SillyTavernContext,
  franchiseDisplay: string,
  targetCount: number,
): Promise<GeneratedEntry[]> {
  return runGeneration(
    () => ctx.generateRaw({ prompt: buildGenerationPrompt(franchiseDisplay, targetCount), responseLength: 2048 }),
    'generateUniverseEntries',
    true,
  );
}

/**
 * Generate story-derived entries for the per-chat book. Glue: uses `generateQuietPrompt` so the
 * model DOES see the current chat. An empty result is valid here (nothing notable happened yet).
 */
export async function generateStoryEntries(
  ctx: SillyTavernContext,
  franchiseDisplay: string,
  softCap: number,
): Promise<GeneratedEntry[]> {
  return runGeneration(
    () => ctx.generateQuietPrompt({ quietPrompt: buildStoryPrompt(franchiseDisplay, softCap), skipWIAN: true, responseLength: 2048 }),
    'generateStoryEntries',
    false,
  );
}

/** Shared retry/parse loop for a generation call. `requireNonEmpty` distinguishes canon from story. */
async function runGeneration(
  call: () => Promise<string>,
  label: string,
  requireNonEmpty: boolean,
): Promise<GeneratedEntry[]> {
  const maxAttempts = 2;
  let lastError: unknown;
  for (let attempt = 0; attempt < maxAttempts; attempt++) {
    let raw: string;
    try {
      raw = await call();
    } catch (error) {
      lastError = error;
      continue;
    }
    try {
      const entries = parseGenerationResponse(raw);
      if (entries.length > 0 || !requireNonEmpty) return entries;
      lastError = new Error('generation returned an empty entry list');
    } catch (error) {
      lastError = error;
    }
  }
  throw new Error(`${label}: no usable result after ${maxAttempts} attempts (${String(lastError)})`);
}
